apiVersion: v1
kind: Service
metadata:
  name: stress-ng-server
spec:
  selector:
    app: stress-ng-server
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng-server
spec:
  selector:
    matchLabels:
      app: stress-ng-server
  replicas: 5
  template:
    metadata:
      labels:
        app: stress-ng-server
    spec:
      containers:
      - name: stress-ng-server
        image: stress-ng-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000