apiVersion: v1
kind: Service
metadata:
  name: stress-ng-server
spec:
  selector:
    app: stress-ng-server
  ports:
  - protocol: "TCP"
    port: 8700
    targetPort: 8700

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng-server
spec:
  selector:
    matchLabels:
      app: stress-ng-server
  replicas: 1
  template:
    metadata:
      labels:
        app: stress-ng-server
    spec:
      containers:
      - name: stress-ng-server
        image: shubhank19/stress-ng-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8700